apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-dev

# namePrefix is used to add a prefix to the names of all resources in this kustomization. 
# This is useful for distinguishing between different environments (e.g., dev, staging, prod) 
# when deploying the same set of resources.
namePrefix: dev-

resources:
  - namespace.yaml
  - ../../base

images:
  - name: nginx
    newTag: "1.27"

patches:
  - path: patch-replicas.yaml
    target:
      kind: Deployment
      name: hello-kustomize
