apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kustomize
  template:
    metadata:
      labels:
        app: hello-kustomize
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

